import * as React from 'react';
import { twMerge } from 'tailwind-merge';
import { clsx, type ClassValue } from 'clsx';
export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }
export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn('rounded-2xl border border-border bg-card/80 p-5 shadow-glow backdrop-blur', className)} {...props} />; }
export function Badge({ className, ...props }: React.HTMLAttributes<HTMLSpanElement>) { return <span className={cn('inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-medium', className)} {...props} />; }
export function Button({ className, disabled, title, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button disabled={disabled} aria-disabled={disabled || undefined} title={title || (disabled ? 'Disabled by current dashboard posture' : undefined)} className={cn('rounded-lg border border-border bg-muted px-3 py-2 text-sm transition hover:bg-accent/20 focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-300 disabled:cursor-not-allowed disabled:opacity-55', className)} {...props} />; }
export function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input className={cn('w-full rounded-xl border border-border bg-slate-950/60 px-3 py-2 text-sm outline-none ring-primary/40 placeholder:text-slate-500 focus:ring-2', className)} {...props} />; }
export function EmptyState({ title, body }: { title: string; body: string }) { return <Card className="border-dashed text-center" role="status"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-300">{body}</p></Card>; }
export function ActionNotice({ mode = 'read-only', children }: { mode?: 'read-only' | 'demo' | 'live'; children: React.ReactNode }) { const tone = mode === 'live' ? 'border-emerald-400/30 bg-emerald-500/10 text-emerald-100' : mode === 'demo' ? 'border-sky-400/30 bg-sky-500/10 text-sky-100' : 'border-amber-400/30 bg-amber-500/10 text-amber-100'; return <div className={cn('rounded-xl border p-3 text-sm', tone)} role="status">{children}</div>; }
